baseURL = 'https://github.com/spatial-data-scientist/portfolio'
languageCode = 'en-us'
title = "Elias Haglund's Portfolio"
theme = 'tailblissfork'

[params]
  description = "Welcome to my portfolio website!"

[build]
  writeStats = true
