baseURL = 'https://github.com/spatial-data-scientist/portfolio'
languageCode = 'en-us'
title = 'Elias Haglund Portfolio'
theme = 'hugo-theme-pico'

[params]
  description = "A brief description of my site"