baseURL = 'https://github.com/spatial-data-scientist/portfolio'
languageCode = 'en-us'
title = 'Elias Haglund Portfolio'
theme = 'toha'

[params]
  description = "A brief description of my site"

[build]
  writeStats = true
