baseURL = 'https://github.com/spatial-data-scientist/portfolio'
languageCode = 'en-us'
title = "Elias Haglund"
theme = 'tailblissfork'

[params]
  description = "Portfolio"

[build]
  writeStats = true
