name = "Hugo-Portfolio"
description = "A simple one page portfolio in Bootstrap with light theme"

license = "GNU GPLv3"
licenselink = "https://github.com/maheenwaris/hugo-portfolio/blob/main/LICENSE"
homepage = "https://github.com/maheenwaris/hugo-portfolio"
demosite = "https://hugo-portfolio.maheenwaris.com/"

tags = ["minimal", "portfolio", "personal", "bootstrap"]

authors = [
  {name = "Maheen Waris", homepage = "https://maheenwaris.com"},
]

min_version = "0.111.3"
